[package]
name = "tsm-sys"
version = "0.1.0"
authors = ["Andy Hartford <andy.hartford@cohealo.com>"]
links = "libtsm"
build = "build.rs"

[build-dependencies]
gcc = "0.3"
glob = "0.2.10"
libc = "0.1"

[dev-dependencies]
regex = "0.1.8"
